"""Created Paste model with relationship.

Revision ID: 51d3eb336120
Revises: 6a1f40113b7a
Create Date: 2024-03-11 23:06:14.307273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51d3eb336120'
down_revision: Union[str, None] = '6a1f40113b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paste',
        sa.Column('hash', sa.String(length=6), nullable=False),
        sa.Column('uri', sa.String(length=256), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('hash'),
        sa.UniqueConstraint('uri')
    )
    op.create_index(op.f('ix_paste_hash'), 'paste', ['hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paste_hash'), table_name='paste')
    op.drop_table('paste')
    # ### end Alembic commands ###
